# Generated by Django 5.2.4 on 2025-08-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionClinica',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateTimeField()),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('detalle_clinico', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atencion_clinica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtencionInsumo',
            fields=[
                ('pk', models.CompositePrimaryKey('id_atencion', 'id_insumo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad_utilizada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_asociado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dosis', models.CharField(blank=True, max_length=100, null=True)),
                ('via_administracion', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atencion_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicaServicio',
            fields=[
                ('pk', models.CompositePrimaryKey('id_clinica', 'id_servicio_detalle', blank=True, editable=False, primary_key=True, serialize=False)),
                ('costo_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinica_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicaVeterinaria',
            fields=[
                ('id_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('rut_clinica', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('sitio_web', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinica_veterinaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('url_archivo', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documento_adjunto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsumoClinico',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_insumo', models.CharField(blank=True, max_length=50, null=True)),
                ('principio_activo', models.CharField(blank=True, max_length=100, null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_base', models.CharField(blank=True, max_length=20, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insumo_clinico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nro_chip', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('patron', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_reproductivo', models.BooleanField(blank=True, null=True)),
                ('modo_obtencion', models.CharField(blank=True, max_length=50, null=True)),
                ('razon_tenencia', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_vital', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('consentimiento', models.BooleanField(blank=True, null=True)),
                ('fecha_consentimiento', models.DateField(blank=True, null=True)),
                ('url_doc_consentimiento', models.TextField(blank=True, null=True)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mascota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nacionalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalClinica',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('nro_documento', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal_clinica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalEspecialidad',
            fields=[
                ('pk', models.CompositePrimaryKey('id_personal', 'id_especialidad', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal_especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalNacionalidad',
            fields=[
                ('pk', models.CompositePrimaryKey('id_personal', 'id_nacionalidad', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal_nacionalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_receta', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('indicaciones_generales', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('id_receta_item', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_item', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_item', models.CharField(blank=True, max_length=100, null=True)),
                ('dosis', models.CharField(blank=True, max_length=50, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=50, null=True)),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('via_administracion', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recomendado_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receta_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioDetalle',
            fields=[
                ('id_servicio_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicio_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('nro_documento', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorNacionalidad',
            fields=[
                ('pk', models.CompositePrimaryKey('id_tutor', 'id_nacionalidad', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tutor_nacionalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.TextField()),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('rol', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_sesion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
