# Generated by Django 5.2.4 on 2025-08-12 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('motivo_atencion', models.TextField()),
                ('detalle_clinico', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_clinica', models.ForeignKey(db_column='id_clinica', on_delete=django.db.models.deletion.CASCADE, to='core.clinicaveterinaria')),
                ('id_mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='core.mascota')),
                ('id_personal', models.ForeignKey(db_column='id_personal', on_delete=django.db.models.deletion.CASCADE, to='core.personalclinica')),
                ('id_servicio_detalle', models.ForeignKey(db_column='id_servicio_detalle', on_delete=django.db.models.deletion.CASCADE, to='core.serviciodetalle')),
            ],
            options={
                'verbose_name': 'Atención Médica',
                'verbose_name_plural': 'Atenciones Médicas',
                'db_table': 'atencion_medica',
                'ordering': ['-fecha_atencion', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAtencion',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('RADIOGRAFIA', 'Radiografía'), ('ANALISIS_SANGRE', 'Análisis de Sangre'), ('ECOGRAFIA', 'Ecografía'), ('HISTORIA_CLINICA', 'Historia Clínica'), ('RECETA', 'Receta'), ('CERTIFICADO', 'Certificado'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos_atencion/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_atencion', models.ForeignKey(db_column='id_atencion', on_delete=django.db.models.deletion.CASCADE, to='atencion_medica.atencionmedica')),
            ],
            options={
                'verbose_name': 'Documento de Atención',
                'verbose_name_plural': 'Documentos de Atención',
                'db_table': 'documento_atencion',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
